INSERT INTO campuses (name, city, subtitle, summary, vibe, latitude, longitude)
VALUES
  ('North Quad', 'Campus City', 'Quiet and academic', 'Best for focused study blocks and library culture.', 'Deep focus', 40.4419, -79.9431),
  ('Innovation District', 'Campus City', 'Productive and social', 'Ideal for group work, review sessions, and collaborative study.', 'Group review', 40.4429, -79.9418),
  ('Student Hub', 'Campus City', 'Coffee and calm energy', 'Great for flexible study sessions with community energy.', 'Creative flow', 40.4397, -79.9412),
  ('Arts Courtyard', 'Campus City', 'Calm and scenic', 'Perfect for reading and low-pressure outdoor sessions.', 'Light focus', 40.4435, -79.9473)
ON CONFLICT DO NOTHING;

INSERT INTO study_spots (
  campus_id,
  name,
  building,
  address,
  distance,
  noise_level,
  wifi_quality,
  outlets,
  busyness,
  rating,
  review_count,
  latitude,
  longitude,
  image_url,
  vibe,
  map_x,
  map_y,
  summary,
  tags,
  features,
  open_until,
  category,
  review_highlights
)
VALUES
  (
    1,
    'Harbor Library Nook',
    'Main Library',
    'Main Library, 100 Campus Way, North Quad',
    '0.2 mi',
    1,
    5,
    5,
    2,
    4.9,
    184,
    40.4415,
    -79.9440,
    'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=1200&q=80',
    'Quiet and focused',
    24,
    55,
    'Best for deep work, silent study blocks, and reliable Wi‑Fi.',
    ARRAY['Quiet', 'Fast Wi‑Fi', 'Power outlets'],
    ARRAY['Silent zones', 'Charging desks', 'Natural light'],
    '10:00 PM',
    'Library',
    ARRAY['Highest student rating', 'Perfect for finals prep', 'Strongest Wi‑Fi']
  ),
  (
    2,
    'Innovation Lab Lounge',
    'STEM Center',
    'STEM Center, 240 Research Lane, Innovation District',
    '0.6 mi',
    2,
    5,
    5,
    3,
    4.8,
    142,
    40.4429,
    -79.9418,
    'https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1200&q=80',
    'Productive and social',
    53,
    34,
    'A solid mix of collaboration and focus with plenty of desk space and screens.',
    ARRAY['Group work', 'Strong Wi‑Fi', 'High mobility'],
    ARRAY['Whiteboards', 'Monitor stations', 'USB ports'],
    '9:30 PM',
    'Co-working space',
    ARRAY['Best for team projects', 'Excellent charging access', 'Very productive energy']
  ),
  (
    3,
    'Greenhouse Café',
    'Student Union',
    'Student Union Plaza, 88 Social Avenue, Student Hub',
    '0.8 mi',
    3,
    4,
    4,
    4,
    4.6,
    96,
    40.4397,
    -79.9412,
    'https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&w=1200&q=80',
    'Buzzing but energizing',
    72,
    62,
    'Great for active study sessions with snacks, coffee, and a social rhythm.',
    ARRAY['Coffee', 'Group study', 'Social vibe'],
    ARRAY['Barista coffee', 'Long tables', 'Lounge seating'],
    '11:00 PM',
    'Silent café',
    ARRAY['Good coffee and energy', 'Strong social atmosphere', 'Nice for short blocks']
  ),
  (
    4,
    'Sunset Garden Courtyard',
    'Arts Quad',
    'Arts Quad, 30 Meadow Lane, Arts Courtyard',
    '1.1 mi',
    2,
    3,
    2,
    2,
    4.5,
    78,
    40.4435,
    -79.9473,
    'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80',
    'Calm and refreshing',
    38,
    74,
    'Perfect for reading, journaling, or low-pressure outdoor study sessions.',
    ARRAY['Outdoor', 'Low traffic', 'Nature'],
    ARRAY['Shade seating', 'Outdoor tables', 'Scenic view'],
    '8:30 PM',
    'Outdoor quiet zone',
    ARRAY['Great for reading', 'Relaxed environment', 'A calmer reset spot']
  );
